import type { Metadata } from 'next'
import '../globals.css'
import Link from 'next/link'


export const metadata: Metadata = {
  title: 'My Personal Awesome Site',
  description: 'Generated by create next app and Sanity CMS',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='max-w-3xl mx-auto py-10'>

        <header>
          <Link href='/'
            className=' text-lg font-bold bg-gradient-to-r from-red-500 via-blue-500 to-yellow-500 bg-clip-text text-transparent'
          >
            Flash
          </Link>
        </header>

        <main className='py-20'>{children}</main>
      </body>
    </html>
  )
}
