import type { Metadata } from 'next'
import '../globals.css'
import Link from 'next/link'
import { getPages } from '@/sanity/sanity-utils'


export const metadata: Metadata = {
  title: 'My Personal Awesome Site',
  description: 'Generated by create next app and Sanity CMS',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // get all pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className='max-w-3xl mx-auto py-10'>

        <header className="flex items-center justify-between">
          <Link href='/'
            className=' text-lg font-bold bg-gradient-to-r from-red-500 via-blue-500 to-yellow-500 bg-clip-text text-transparent'
          >
            Flash
          </Link>
          <div className="flex items-center gap-5 text-sm text-gray-600">
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className='hover:underline'
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>

        <main className='py-20'>{children}</main>
      </body>
    </html>
  )
}
